### ISSUE TITLE
Integration into Xenia mousehook fork?

### ISSUE THREAD

**Issue by Clippy95** [DottierGalaxy50/rdr-pc-controls-xenia#1]
Are you interested to have this integrated into this fork of Xenia? 
Not only it would be easier for users but ~~maybe also make it work with patches? the table as of now doesn't work with patches, (60 fps patch to be precise)~~

I'm [implementing](https://github.com/marinesciencedude/xenia-canary-mousehook/pull/29) it now 

https://github.com/marinesciencedude/xenia-canary-mousehook

**Comment by DottierGalaxy50** [comment]
I checked it out and i think it would be cool, but I'm doing some other things now so i wouldn't be doing much until i finish them, however, if you can do it yourself feel free to do so. If you think about doing it then i could help. As for the patches, i will make the script compatible with the current ones in the near future.

**Comment by Clippy95** [comment]
> I checked it out and i think it would be cool, but I'm doing some other things now so i wouldn't be doing much until i finish them, however, if you can do it yourself feel free to do so. If you think about doing it then i could help. As for the patches, i will make the script compatible with the current ones in the near future.

Could you join the [Xenia discord](https://discord.gg/Q9mxZf9) and maybe talk with marinesciencedude in the server? there is a mousehook thread in #media_only, he does not own the GOTY version of the game and would like your help and to know what you're doing with the table

**Comment by Clippy95** [comment]
I think this can be closed since I practically finished it with this [pull request](https://github.com/marinesciencedude/xenia-canary-mousehook/pull/29)
Thank you for the help and this table
