### ISSUE TITLE
Failed to launch title path is invalid

### ISSUE THREAD

**Issue by CripledCod** [DottierGalaxy50/rdr-pc-controls-xenia#2]
I keep receiving an error when I load up the batch file.

**Comment by DottierGalaxy50** [comment]
Did you add the path of the RDR's iso into the batch file? If not you have to replace "path/to/game.iso" with the iso's path. If that doesn't work you can just open xenia and the trainer manually.

**Comment by CripledCod** [comment]
Sorry I didn't know I had to do that
